### ISSUE TITLE
Can it be ported to rails 4?

### ISSUE THREAD

**Issue by alagunambi** [jrmyward/honor#2]
Hi, I would like to port this gem to rails 4, any pointers?

**Comment by bercht** [comment]
Hi, have you some news for Rails 4 ? :)

**Comment by albertpak** [comment]
@alagunambi Does this work well with Rails 4.2?

**Comment by jrmyward** [comment]
It is not currently compatible with Rails 4. 

I'm hoping to update the gem soon. I would welcome a PR for the update if you're interested.

Jeremy

**Comment by rahul100885** [comment]
Guys version 2.0.1 is made compatible with rails 4. Try it..

**Comment by jrmyward** [comment]
https://github.com/jrmyward/honor/pull/3 fixes this issue. 

Thanks again @rahul100885 for the PR!
