### ISSUE TITLE
Does the leaderboard automatically reset itself at the start of each period?

### ISSUE THREAD

**Issue by monroemann** [jrmyward/honor#8]
For example, this code:

`@weekly_leaderboard   = Honor::Scorecard.leaderboard(user_ids, rank_by: 'weekly', sort_direction: 'desc')`

Will that reset at midnight every Monday morning?  Or do we have to manually reset it?

Thanks!
-Monroe

**Comment by monroemann** [comment]
@jrmyward @alexkroman @rahul100885 Just wanted to see if you saw my question above.  Thanks!

**Comment by jrmyward** [comment]
`Scorecard. reset_weekly_scores` controls that. Under the hood it uses Rails' `beginning_of_week` which defaults to Monday. 

https://api.rubyonrails.org/classes/Date.html#method-c-beginning_of_week

If you want to automatically recalculate them on a particular schedule, you'll need to call them from a cron job.

Hope this helps!

**Comment by monroemann** [comment]
So if we are fine with Monday as beginning of week, then it will automatically reset the leaderboard automatically each Monday without having to call "Scorecard. reset_weekly_scores" or do we still have to do that?
